insert into barkeep_bottles (name, category, sort_order, style) values
  ('Hendrick''s Flora & Fauna Gin', 'Base Spirits', 0, '{"shape":"apothecary","glass":"#1e1b22","liquid":"#1e1b22","label":"#e8dcc4","labelText":"HENDRICK''S","accent":"#4b7a6a"}'::jsonb),
  ('St. George Botanivore Gin', 'Base Spirits', 1, '{"shape":"tall","glass":"#d9e4e2","liquid":"#eef2f0","label":"#f2ebdd","labelText":"ST. GEORGE","accent":"#2e5a3a"}'::jsonb),
  ('Tanqueray London Dry Gin', 'Base Spirits', 2, '{"shape":"standard","glass":"#1f6b3a","liquid":"#1f6b3a","label":"#e4e4e4","labelText":"TANQUERAY","accent":"#c8102e"}'::jsonb),
  ('Kettle One Vodka', 'Base Spirits', 3, '{"shape":"tall","glass":"#d9e4e2","liquid":"#eef2f0","label":"#f4f1e8","labelText":"KETEL ONE","accent":"#1e3a6e"}'::jsonb),
  ('Skyy Vodka', 'Base Spirits', 4, '{"shape":"tall","glass":"#1f4fb5","liquid":"#1f4fb5","label":"#1f4fb5","labelText":"SKYY","accent":"#e8ecf0"}'::jsonb),
  ('Smirnoff Spicy Tamarind', 'Base Spirits', 5, '{"shape":"tall","glass":"#d9e4e2","liquid":"#c8551a","label":"#b5121b","labelText":"SMIRNOFF","accent":"#f5d26a"}'::jsonb),
  ('Kirkland Silver Tequila', 'Base Spirits', 6, '{"shape":"tall","glass":"#d9e4e2","liquid":"#eef2f0","label":"#c8102e","labelText":"KIRKLAND","accent":"#f5f0e6"}'::jsonb),
  ('Kirkland Tequila Blanca', 'Base Spirits', 7, '{"shape":"standard","glass":"#d9e4e2","liquid":"#eef2f0","label":"#1e3a6e","labelText":"KIRKLAND","accent":"#f5f0e6"}'::jsonb),
  ('Recuerdo Mezcal', 'Base Spirits', 8, '{"shape":"squat","glass":"#d9e4e2","liquid":"#f0eee6","label":"#2b2b2b","labelText":"RECUERDO","accent":"#d9a441"}'::jsonb),
  ('Masterson''s 10 Year Straight Rye', 'Whiskey', 0, '{"shape":"standard","glass":"#d9e4e2","liquid":"#b8651b","label":"#2a1e14","labelText":"MASTERSON''S","accent":"#c9a24b"}'::jsonb),
  ('Bulleit Rye', 'Whiskey', 1, '{"shape":"flask","glass":"#d9e4e2","liquid":"#c2701e","label":"#2f7a4b","labelText":"BULLEIT","accent":"#f1e9d6"}'::jsonb),
  ('Angel''s Envy Bourbon', 'Whiskey', 2, '{"shape":"decanter","glass":"#d9e4e2","liquid":"#b5581b","label":"#f2ead9","labelText":"ANGEL''S ENVY","accent":"#8c1d2a"}'::jsonb),
  ('Royal Suntory Whisky', 'Whiskey', 3, '{"shape":"squat","glass":"#d9e4e2","liquid":"#b9702a","label":"#f3ebd8","labelText":"SUNTORY","accent":"#1a2a44"}'::jsonb),
  ('Teeling Irish Whiskey', 'Whiskey', 4, '{"shape":"standard","glass":"#d9e4e2","liquid":"#c68a2e","label":"#1f1f1f","labelText":"TEELING","accent":"#c9a24b"}'::jsonb),
  ('Pusser''s Rum', 'Rum', 0, '{"shape":"standard","glass":"#d9e4e2","liquid":"#6b3a15","label":"#1e3a6e","labelText":"PUSSER''S","accent":"#f1e9d6"}'::jsonb),
  ('Gosling''s Black Seal Rum', 'Rum', 1, '{"shape":"standard","glass":"#141210","liquid":"#141210","label":"#f2ead9","labelText":"GOSLING''S","accent":"#141210"}'::jsonb),
  ('Barbancourt Haitian White Rum', 'Rum', 2, '{"shape":"standard","glass":"#d9e4e2","liquid":"#eef2f0","label":"#f4f1e8","labelText":"BARBANCOURT","accent":"#1b5e3b"}'::jsonb),
  ('Bacardi White Rum', 'Rum', 3, '{"shape":"tall","glass":"#d9e4e2","liquid":"#eef2f0","label":"#f4f1e8","labelText":"BACARDI","accent":"#c8102e"}'::jsonb),
  ('Captain Morgan Spiced Rum', 'Rum', 4, '{"shape":"standard","glass":"#d9e4e2","liquid":"#c27a2a","label":"#f5e6c4","labelText":"CAPTAIN MORGAN","accent":"#8c1d2a"}'::jsonb),
  ('Tahitian Manutea Rum', 'Rum', 5, '{"shape":"tall","glass":"#d9e4e2","liquid":"#f0e6c8","label":"#1e6f8e","labelText":"MANUTEA","accent":"#f5f0e6"}'::jsonb),
  ('Mamajuana', 'Rum', 6, '{"shape":"apothecary","glass":"#d9e4e2","liquid":"#6e4520","label":"#c9a24b","labelText":"MAMAJUANA","accent":"#3b2410"}'::jsonb),
  ('Green Chartreuse', 'Chartreuse Family', 0, '{"shape":"squat","glass":"#d9e4e2","liquid":"#3e8e3a","label":"#f4efdd","labelText":"CHARTREUSE","accent":"#1f5a2a"}'::jsonb),
  ('Yellow Chartreuse', 'Chartreuse Family', 1, '{"shape":"squat","glass":"#d9e4e2","liquid":"#e8c43a","label":"#f4efdd","labelText":"CHARTREUSE","accent":"#b8901b"}'::jsonb),
  ('MOF Yellow Chartreuse', 'Chartreuse Family', 2, '{"shape":"squat","glass":"#d9e4e2","liquid":"#e3b92e","label":"#1e1e1e","labelText":"M.O.F.","accent":"#e8c43a"}'::jsonb),
  ('Chartreuse Liqueur d''Élixir 1605', 'Chartreuse Family', 3, '{"shape":"squat","glass":"#d9e4e2","liquid":"#4c9b45","label":"#f4efdd","labelText":"1605","accent":"#3a6e2e"}'::jsonb),
  ('Chartreuse Végétal', 'Chartreuse Family', 4, '{"shape":"dasher","glass":"#7a5230","liquid":"#7a5230","label":"#f4efdd","labelText":"VÉGÉTAL","accent":"#2e7a34"}'::jsonb),
  ('Campari', 'Aperitifs & Vermouth', 0, '{"shape":"standard","glass":"#d9e4e2","liquid":"#d9102a","label":"#f4f1e8","labelText":"CAMPARI","accent":"#d9102a"}'::jsonb),
  ('St-Germain Elderflower Liqueur', 'Aperitifs & Vermouth', 1, '{"shape":"decanter","glass":"#d9e4e2","liquid":"#f1e8b8","label":"#f4efdd","labelText":"ST-GERMAIN","accent":"#b08d2b"}'::jsonb),
  ('Lillet Blanc', 'Aperitifs & Vermouth', 2, '{"shape":"standard","glass":"#dce8d8","liquid":"#f0e9c0","label":"#f4efdd","labelText":"LILLET","accent":"#c8a64b"}'::jsonb),
  ('Dry Vermouth', 'Aperitifs & Vermouth', 3, '{"shape":"standard","glass":"#d8e6d6","liquid":"#f0ecd0","label":"#f4f1e8","labelText":"DRY VERMOUTH","accent":"#2e6e4e"}'::jsonb),
  ('Sweet (Red) Vermouth', 'Aperitifs & Vermouth', 4, '{"shape":"standard","glass":"#d9e4e2","liquid":"#7a2a1e","label":"#f4f1e8","labelText":"SWEET VERMOUTH","accent":"#8c1d2a"}'::jsonb),
  ('Fernet-Branca', 'Amari & Digestifs', 0, '{"shape":"standard","glass":"#d9e4e2","liquid":"#2a1a12","label":"#f2ead9","labelText":"FERNET-BRANCA","accent":"#1f4e8c"}'::jsonb),
  ('Fernet Branca Menta', 'Amari & Digestifs', 1, '{"shape":"standard","glass":"#d9e4e2","liquid":"#2a1a12","label":"#2e9e6b","labelText":"BRANCA MENTA","accent":"#f2ead9"}'::jsonb),
  ('Amaro Nonino', 'Amari & Digestifs', 2, '{"shape":"tall","glass":"#d9e4e2","liquid":"#b8641e","label":"#f4efdd","labelText":"NONINO","accent":"#7a1e2a"}'::jsonb),
  ('Facciabruta Centerbe', 'Amari & Digestifs', 3, '{"shape":"tall","glass":"#d9e4e2","liquid":"#2e8b3a","label":"#1e1e1e","labelText":"CENTERBE","accent":"#e8c43a"}'::jsonb),
  ('Strega', 'Amari & Digestifs', 4, '{"shape":"tall","glass":"#d9e4e2","liquid":"#e8d53a","label":"#f4efdd","labelText":"STREGA","accent":"#2b3f8c"}'::jsonb),
  ('DOM Bénédictine', 'Amari & Digestifs', 5, '{"shape":"squat","glass":"#4b3a1a","liquid":"#4b3a1a","label":"#f4efdd","labelText":"BÉNÉDICTINE","accent":"#8c1d2a"}'::jsonb),
  ('Becherovka', 'Amari & Digestifs', 6, '{"shape":"square","glass":"#2e6e3a","liquid":"#2e6e3a","label":"#f4efdd","labelText":"BECHEROVKA","accent":"#1e4d2a"}'::jsonb),
  ('Corbel Brandy', 'Brandy & Pisco', 0, '{"shape":"standard","glass":"#d9e4e2","liquid":"#b8651b","label":"#1e1e1e","labelText":"CORBEL","accent":"#c9a24b"}'::jsonb),
  ('Kirschwasser', 'Brandy & Pisco', 1, '{"shape":"tall","glass":"#d9e4e2","liquid":"#eef2f0","label":"#f4f1e8","labelText":"KIRSCH","accent":"#8c1d2a"}'::jsonb),
  ('Viña de Oro Pisco', 'Brandy & Pisco', 2, '{"shape":"standard","glass":"#d9e4e2","liquid":"#f0eee6","label":"#1e3a6e","labelText":"VIÑA DE ORO","accent":"#c9a24b"}'::jsonb),
  ('Luxardo Maraschino', 'Liqueurs', 0, '{"shape":"squat","glass":"#c9b27a","liquid":"#c9b27a","label":"#2e7a3a","labelText":"LUXARDO","accent":"#f4efdd"}'::jsonb),
  ('Mr. Black Coffee Liqueur', 'Liqueurs', 1, '{"shape":"apothecary","glass":"#d9e4e2","liquid":"#17110e","label":"#f4efdd","labelText":"MR BLACK","accent":"#17110e"}'::jsonb),
  ('Baileys Irish Cream', 'Liqueurs', 2, '{"shape":"standard","glass":"#2a1f16","liquid":"#2a1f16","label":"#3a2a1c","labelText":"BAILEYS","accent":"#f1e3c8"}'::jsonb),
  ('Velvet Falernum', 'Liqueurs', 3, '{"shape":"tall","glass":"#d9e4e2","liquid":"#f0e6c8","label":"#1e5a6e","labelText":"FALERNUM","accent":"#f4efdd"}'::jsonb),
  ('Disaronno Amaretto', 'Liqueurs', 4, '{"shape":"square","glass":"#d9e4e2","liquid":"#b8651b","label":"#f4efdd","labelText":"DISARONNO","accent":"#1e1e1e"}'::jsonb),
  ('DeKuyper Triple Sec', 'Liqueurs', 5, '{"shape":"standard","glass":"#d9e4e2","liquid":"#eef2f0","label":"#f4f1e8","labelText":"TRIPLE SEC","accent":"#e67e22"}'::jsonb),
  ('Peppermint Schnapps', 'Liqueurs', 6, '{"shape":"tall","glass":"#d9e4e2","liquid":"#eef2f0","label":"#f4f1e8","labelText":"PEPPERMINT","accent":"#1e8e5a"}'::jsonb),
  ('Limoncello', 'Liqueurs', 7, '{"shape":"tall","glass":"#d9e4e2","liquid":"#f2e84a","label":"#f4f1e8","labelText":"LIMONCELLO","accent":"#2b7a3a"}'::jsonb),
  ('Licor 43', 'Liqueurs', 8, '{"shape":"tall","glass":"#d9e4e2","liquid":"#e8b83a","label":"#f4efdd","labelText":"43","accent":"#8c1d2a"}'::jsonb),
  ('Edinburgh Rhubarb & Ginger', 'Liqueurs', 9, '{"shape":"tall","glass":"#d9e4e2","liquid":"#e08aa0","label":"#f4efdd","labelText":"EDINBURGH","accent":"#b03a5a"}'::jsonb),
  ('Crème de Violette', 'Liqueurs', 10, '{"shape":"tall","glass":"#d9e4e2","liquid":"#5b3a8c","label":"#f4efdd","labelText":"VIOLETTE","accent":"#5b3a8c"}'::jsonb),
  ('Port', 'Liqueurs', 11, '{"shape":"standard","glass":"#1a1410","liquid":"#1a1410","label":"#f4efdd","labelText":"PORT","accent":"#6e1e2a"}'::jsonb),
  ('Angostura Bitters', 'Bitters & Garnishes', 0, '{"shape":"dasher","glass":"#d9e4e2","liquid":"#5a2a14","label":"#f4efdd","labelText":"ANGOSTURA","accent":"#e8b83a"}'::jsonb),
  ('Orange Bitters', 'Bitters & Garnishes', 1, '{"shape":"dasher","glass":"#d9e4e2","liquid":"#c25a1e","label":"#f4efdd","labelText":"ORANGE","accent":"#e67e22"}'::jsonb),
  ('Peychaud''s Bitters', 'Bitters & Garnishes', 2, '{"shape":"dasher","glass":"#d9e4e2","liquid":"#b5121b","label":"#f4efdd","labelText":"PEYCHAUD''S","accent":"#b5121b"}'::jsonb),
  ('Luxardo Maraschino Cherries', 'Bitters & Garnishes', 3, '{"shape":"jar","glass":"#d9e4e2","liquid":"#3a0e14","label":"#2e7a3a","labelText":"LUXARDO","accent":"#f4efdd"}'::jsonb);
